---
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - TZ=Europe/Rome
      - MYSQL_DATABASE=utenti #optional
      - MYSQL_USER=sweng #optional
      - MYSQL_PASSWORD=sweng #optional
      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - ./docker/db:/config
    ports:
      - 3306:3306
    restart: unless-stopped
